Fixing random JSDoc issues (#6392)
* Fixing random JSDoc issues that cause spam or other issues in RTI.js logs

* Update src/scene/skin-instance.js

Co-authored-by: Will Eastcott <willeastcott@gmail.com>

* src/scene/skin-instance.js: add @ignore

* ForwardRenderer fix for: error TS1016: A required parameter cannot follow an optional parameter.

---------

Co-authored-by: Will Eastcott <willeastcott@gmail.com>